fix a lot of stuff
Fix conflicts

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -1,92 +1,30 @@
-###
-### UTILS
-###
+#!/bin/bash
 
-# shellcheck disable=SC2034
-red="\033[91m"
-# shellcheck disable=SC2034
-green="\033[92m"
-# shellcheck disable=SC2034
-blue="\033[94m"
-# shellcheck disable=SC2034
-yellow="\033[93m"
-# shellcheck disable=SC2034
-white="\033[97m"
-# shellcheck disable=SC2034
-no_color="\033[0m"
-gray="\033[90m"
+# Save this file as ~/.config/yadm/bootstrap and make it executable. It will
+# execute all executable files (excluding templates and editor backups) in the
+# ~/.config/yadm/bootstrap.d directory when run.
+print_header
 
+set -eu
 
-## check if /tmp dir exists
+# Directory to look for bootstrap executables in
+BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
 
-
-print_discreet_no_nl() {
-    echo "${gray}=>${no_color}${gray}" "${@}" "${no_color}" >&1
-}
-
-print_discreet() {
-    echo "${gray}=>${no_color}${gray}" "${@}" "${no_color}" >&1
-}
-print_msg() {
-    echo "${green}=>${no_color}${white}" "${@}" "${no_color}" >&1
-}
-
-print_warning() {
-    echo "${yellow}=> WARNING:${no_color}${white}" "${@}" "${no_color}" >&2
-}
-
-print_error() {
-    echo "${red}=> ERROR:${no_color}${white}" "${@}" "${no_color}" >&2
-}
-
-###
-### Install brew deps
-###
-brew bundle  --file=~/.config/brew/Brewfile --quiet install
-
-
-###
-### ZSH
-###
-if [ "$SHELL" != "$(which zsh)" ]; then
-    sudo sh -c "echo $(which zsh) >> /etc/shells"
-    chsh -s $(which zsh); 
+if [[ ! -d "$BOOTSTRAP_D" ]]; then
+    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
+    exit 1
 fi
 
-###
-### OH MY ZSH!
-###
-if [ ! -d "$HOME/.oh-my-zsh" ]; then
-    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended --keep-zshrc"
-fi
+declare -a bootstraps
+while IFS= read -r bootstrap; do
+    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ ~$ ]]; then
+        bootstraps+=("$bootstrap")
+    fi
+done < <(find -L "$BOOTSTRAP_D" -type f | sort)
 
-if [ ! -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions" ]; then
-    git  clone https://github.com/zsh-users/zsh-autosuggestions.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
-fi
-
-if [ ! -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting" ]; then
-    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
-fi 
-
-if [ ! -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting" ]; then
-    git clone https://github.com/zdharma-continuum/fast-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting
-fi
-if [ ! -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autocomplete" ]; then
-    git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autocomplete
-fi
-
-
-###
-### iTerm conf
-###
-defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
-defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
-
-
-###
-### PowerLevel10k
-###
-if [ ! -d  "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k" ]; then
-    cd ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes
-    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git 
-fi
+for bootstrap in "${bootstraps[@]}"; do
+    if ! "$bootstrap"; then
+        echo "Error: bootstrap '$bootstrap' failed" >&2
+        exit 1
+    fi
+done
